### ISSUE TITLE
How to install Energi Core Node to stake with GEN3 on my Raspberry Pi

### ISSUE THREAD

**Issue by FCU4ever** [energicryptocurrency/energi3#6]
Hello,

I've got the Energi Core Wallet (v2) working on my Raspberry Pi using this guide:
https://github.com/zalam003/energi/blob/master/how_to_build_energi_binaries_on_RPi.txt

Now the migration to GEN3 starts tomorrow, I have to install the Energi Core Node to keep staking on my Raspberry Pi. Is their someone who can help me to get this working?

**Comment by andvgal** [comment]
Please use official support channels: https://docs.energi.software/en/support/help-me

You can try to use Linux ARMv6 builds from the downloads sections. Otherwise, you'll need to create your own build.
